lstTokens = {'/*':'tk_ini_Coment',
            'texto':'tk_texto',
            '*/':'tk_fin_coment',
            'identificador':'tk_identificacador',
            'let':'tk_declaracion',
            '=':'tk_igual',
            'true':'tk_Bool_verd',
            'false':'tk__Bool_falso',
            'var':'tk_variable',
            'const':'tk_constante',
            ';':'tk_punto_coma',
            '"':'tk_comilla',
            'if':'tk_Oper_if',
            '(':'tk_Par_ini',
            ')':'tk_Par_fin',
            '{':'tk_llave_ini',
            '}':'tk_llave_fin',
            'while':'tk_ciclo_while',
            'foreach':'tk_ciclo_foreach',
            'switch':'tk_sentencia_switch',
            'case':'tk_caso',
            'numero':'tk_numero',
            'break':'tk_parar',
            'default':'tk_porDefecto',
            ':':'tk_dos_puntos',
            ',':'tk_coma',
            '=>':'tk_apuntador',
            'print':'tk_imprimir'
}

desc_Tokens = {'/*':'apertura de comentario en bloque',
            'texto':'texto plano',
            '*/':'cierre de comentario',
            'identificador':'texto que representa un identificador',
            'let':'declara el tipo de variable',
            '=':'signo igual, describe que el valor es igual a',
            'true':'Booleano Verdadero',
            'false':'Booleano Falso',
            'var':'Define un tipo de variable no especifico',
            'const':'Define una variable constante',
            ';':'Determina el final de una linea o funcion',
            '"':'Se utiliza para delimitar texto',
            'if':'operador if, valua un booleano para seguir con la ejecucion',
            '(':'inicia un conjunto de valores',
            ')':'finaliza el conjunto de volores',
            '{':'inicia la agrupacion de codigo a ejecutarse',
            '}':'finaliza la agrupacion de codigo a ejecutarse',
            'while':'ciclo que necesita de una validacion',
            'foreach':'ciclo que itera sobre una agrupacion de elementos',
            'switch':'operador en caso de, hace a referencia a un segmento en especifico',
            'case':'se refiere a una condicion en especifico',
            'numero':'es un numero',
            'break':'finaliza la ejecucion de una bucle.',
            'default':'por defecto, usado para referirse a la opcion inicial',
            ':':'inicio de un caso',
            ',':'separacion de valores',
            '=>':'utilizado para asignar ',
            'print':'utilizado para imprimir'
}